remote-theme: garrettboatman/Blank-Theme-Jekyll
title: Experiments with GitHub Pages
description: Very much always a WIP
permalink: /:title

#############
# Renderers #
#############

markdown: kramdown

sass:
  style: compressed

#########
# Files #
#########

collections_dir: _collections

collections:
  events:
    output: true
    # permalink: /events/:name ## default -> /:collection/:path
  speakers:
    output: false

defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event
      nav: events
  - scope:
      path: ""
    values:
      layout: default

###################
# Site parameters #
###################

domain: mtcoster.github.io

nav:
  - key: home
    name: "Home"
    page: "/"
  - key: events
    name: "Events"
    page: "/events"
  - key: about
    name: "About"
    page: "/about"

fb-app-id: "600131706999745"
fb-page: "TEDxWarwick"
twitter-handle: "TEDxWarwick"

repo: "TEDxWarwickTechnical/tedxwarwicktechnical.github.io"
